name: Node.js GitLab Flow Pipeline

on:
  push:
    branches:
      - develop
      - feature/*
      - hotfix/*
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Deploy application (only on main or hotfix)
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/')
      run: npm run deploy

